# Generated by Django 6.0.6 on 2026-06-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('location_name', models.CharField(max_length=100)),
                ('fill_level', models.IntegerField(default=0)),
                ('gas_value', models.IntegerField(default=0)),
                ('alert_status', models.CharField(choices=[('NOMINAL', 'Nominal Secure'), ('BIN_FULL', 'Critical Warning: Bin Full'), ('METAL', 'Sharps Alert: Metal Found')], default='NOMINAL', max_length=20)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
    ]
