# Generated by Django 6.0.6 on 2026-07-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_smartbin_binfull_smartbin_elementtemp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartbin',
            name='binLevel',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartbin',
            name='heaterState',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartbin',
            name='uvState',
            field=models.BooleanField(default=False),
        ),
    ]
