# Generated by Django 6.0.6 on 2026-07-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_smartbin_binlevel_smartbin_heaterstate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartbin',
            name='pending_command',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
