# Generated by Django 6.0.6 on 2026-08-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_smartbin_pending_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartbin',
            name='last_command',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='smartbin',
            name='last_command_status',
            field=models.CharField(choices=[('NONE', 'No command sent'), ('PENDING', 'Sent — awaiting device confirmation'), ('ACKED', 'Confirmed applied by device')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='smartbin',
            name='last_command_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
