# Generated by Django 6.0.6 on 2026-08-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_telemetryrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartbin',
            name='last_command_status',
            field=models.CharField(choices=[('NONE', 'No command sent'), ('PENDING', 'Sent — awaiting device confirmation'), ('ACKED', 'Confirmed applied by device'), ('TIMEOUT', 'No confirmation received in time')], default='NONE', max_length=10),
        ),
    ]
